In [1]:
import numpy as np
import requests
import time

Q1: Fun with arrays
-

In [2]:
a = np.arange(1,16).reshape(3,5)
a = a[0:5].transpose()

print(a)

b = a[[1, 3], :]
print(b)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]
[[ 2  7 12]
 [ 4  9 14]]


In [3]:
c = np.zeros((4,5),dtype=int)
c[[0,3], :] = 1
c[:,[0,4]] = 1
c

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

---------------
Q2: Histograms
-

In [4]:
url = "https://raw.githubusercontent.com/sbu-python-summer/python-tutorial/master/day-3/sample.txt"
filename = "sample.txt"
r = requests.get(url, allow_redirects=True)

with open(filename, "w") as f:     
    f.write(r.text) 

a = np.loadtxt(filename)
counts, bin_edges = np.histogram(a)

for i in range(len(counts)):
    bin_center = (bin_edges[i] + bin_edges[i+1])/2
    print("Bin center: ", bin_center, "Counts: ", counts[i])


Bin center:  -24.109006493430737 Counts:  6
Bin center:  -11.150163704648554 Counts:  23
Bin center:  1.8086790841336278 Counts:  52
Bin center:  14.767521872915811 Counts:  37
Bin center:  27.726364661697996 Counts:  16
Bin center:  40.68520745048018 Counts:  14
Bin center:  53.64405023926236 Counts:  13
Bin center:  66.60289302804455 Counts:  13
Bin center:  79.56173581682673 Counts:  13
Bin center:  92.5205786056089 Counts:  13


--------------
Q3: Are you faster than numpy? No
-

In [5]:
a = np.linspace(1, 100, 10, endpoint=True)

t0 = time.time()
average = a.sum()/10
sum_square = 0

for i in a:
    b = (i - average)**2
    sum_square += b 
    
std = np.sqrt(sum_square/10)
t1 = time.time()
print("My function took: {} s".format(t1-t0))

t2 = time.time()
std_dev = np.std(a)
t3 = time.time()
print("Numpy took: {} s".format(t3-t2))

print("My function:", std, ", Numpy:", std_dev)


My function took: 0.00010037422180175781 s
Numpy took: 8.606910705566406e-05 s
My function: 31.595094555959157 , Numpy: 31.595094555959157
